package com.russ4stall.pokemon;

/**
 * Created by russellf on 3/10/2016.
 */
public enum Item implements DataField {
    NO_ITEM("00", "No Item"),
    MASTER_BALL("0x01", "Master Ball"),
    ULTRA_BALL("0x02", "Ultra Ball"),
    BRIGHT_POWDER("0x03", "Bright Powder"),
    GREAT_BALL("0x04", "Great Ball"),
    POKE_BALL("0x05", "Poké Ball"),
    BICYCLE("0x06", "Bicycle"),
    MOON_STONE("0x08", "Moon Stone"),
    ANTIDOTE("0x09", "Antidote"),
    BURN_HEAL("0x0A", "Burn Heal"),
    ICE_HEAL("0x0B", "Ice Heal"),
    AWAKENING("0x0C", "Awakening"),
    PARLYZ_HEAL("0x0D", "Parlyz Heal"),
    FULL_RESTORE("0x0E", "Full Restore"),
    MAX_POTION("0x0F", "Max Potion"),
    HYPER_POTION("0x10", "Hyper Potion"),
    SUPER_POTION("0x11", "Super Potion"),
    POTION("0x12", "Potion"),
    ESCAPE_ROPE("0x13", "Escape Rope"),
    REPEL("0x14", "Repel"),
    MAX_ELIXER("0x15", "Max Elixer"),
    FIRE_STONE("0x16", "Fire Stone"),
    THUNDER_STONE("0x17", "Thunder Stone"),
    WATER_STONE("0x18", "Water Stone"),
    HP_UP("0x1A", "HP Up"),
    PROTEIN("0x1B", "Protein"),
    IRON("0x1C", "Iron"),
    CARBOS("0x1D", "Carbos"),
    LUCKY_PUNCH("0x1E", "Lucky Punch"),
    CALCIUM("0x1F", "Calcium"),
    RARE_CANDY("0x20", "Rare Candy"),
    X_ACCURACY("0x21", "X Accuracy"),
    LEAF_STONE("0x22", "Leaf Stone"),
    METAL_POWDER("0x23", "Metal Powder"),
    NUGGET("0x24", "Nugget"),
    POKE_DOLL("0x25", "Poké Doll"),
    FULL_HEAL("0x26", "Full Heal"),
    REVIVE("0x27", "Revive"),
    MAX_REVIVE("0x28", "Max Revive"),
    GUARD_SPEC("0x29", "Guard Spec."),
    SUPER_REPEL("0x2A", "Super Repel"),
    MAX_REPEL("0x2B", "Max Repel"),
    DIRE_HIT("0x2C", "Dire Hit"),
    FRESH_WATER("0x2E", "Fresh Water"),
    SODA_POP("0x2F", "Soda Pop"),
    LEMONADE("0x30", "Lemonade"),
    X_ATTACK("0x31", "X Attack"),
    X_DEFEND("0x33", "X Defend"),
    X_SPEED("0x34", "X Speed"),
    X_SPECIAL("0x35", "X Special"),
    COIN_CASE("0x36", "Coin Case"),
    ITEMFINDER("0x37", "Itemfinder"),
    EXP_SHARE("0x39", "Exp Share"),
    OLD_ROD("0x3A", "Old Rod"),
    GOOD_ROD("0x3B", "Good Rod"),
    SILVER_LEAF("0x3C", "Silver Leaf"),
    SUPER_ROD("0x3D", "Super Rod"),
    PP_UP("0x3E", "PP Up"),
    ETHER("0x3F", "Ether"),
    MAX_ETHER("0x40", "Max Ether"),
    ELIXER("0x41", "Elixer"),
    RED_SCALE("0x42", "Red Scale"),
    SECRET_POTION("0x43", "Secret Potion"),
    SS_TICKET("0x44", "S.S. Ticket"),
    MYSTERY_EGG("0x45", "Mystery Egg"),
    CLEAR_BELL("0x46", "Clear Bell"),
    SILVER_WING("0x47", "Silver Wing"),
    MOOMOO_MILK("0x48", "Moomoo Milk"),
    QUICK_CLAW("0x49", "Quick Claw"),
    PSN_CURE_BERRY("0x4A", "PSN Cure Berry"),
    GOLD_LEAF("0x4B", "Gold Leaf"),
    SOFT_SAND("0x4C", "Soft Sand"),
    SHARP_BEAK("0x4D", "Sharp Beak"),
    PRZ_CURE_BERRY("0x4E", "PRZ Cure Berry"),
    BURNT_BERRY("0x4F", "Burnt Berry"),
    ICE_BERRY("0x50", "Ice Berry"),
    POISON_BARB("0x51", "Poison Barb"),
    KINGS_ROCK("0x52", "King's Rock"),
    BITTER_BERRY("0x53", "Bitter Berry"),
    MINT_BERRY("0x54", "Mint Berry"),
    RED_APRICORN("0x55", "Red Apricorn"),
    TINY_MUSHROOM("0x56", "Tiny Mushroom"),
    BIG_MUSHROOM("0x57", "Big Mushroom"),
    SILVERPOWDER("0x58", "SilverPowder"),
    BLU_APRICORN("0x59", "Blu Apricorn"),
    AMULET_COIN("0x5B", "Amulet Coin"),
    YLW_APRICORN("0x5C", "Ylw Apricorn"),
    GRN_APRICORN("0x5D", "Grn Apricorn"),
    CLEANSE_TAG("0x5E", "Cleanse Tag"),
    MYSTIC_WATER("0x5F", "Mystic Water"),
    TWISTED_SPOON("0x60", "TwistedSpoon"),
    WHT_APRICORN("0x61", "Wht Apricorn"),
    BLACK_BELT("0x62", "Black Belt"),
    BLK_APRICORN("0x63", "Blk Apricorn"),
    PNK_APRICORN("0x65", "Pnk Apricorn"),
    BLACK_GLASSES("0x66", "Black Glasses"),
    SLOWPOKE_TAIL("0x67", "Slowpoke Tail"),
    PINK_BOW("0x68", "Pink Bow"),
    STICK("0x69", "Stick"),
    SMOKE_BALL("0x6A", "Smoke Ball"),
    NEVER_MELT_ICE("0x6B", "Never Melt Ice"),
    MAGNET("0x6C", "Magnet"),
    MIRACLE_BERRY("0x6D", "Miracle Berry"),
    PEARL("0x6E", "Pearl"),
    BIG_PEARL("0x6F", "Big Pearl"),
    EVERSTONE("0x70", "Everstone"),
    SPELL_TAG("0x71", "Spell Tag"),
    RAGE_CANDY_BAR("0x72", "Rage Candy Bar"),
    GS_BALL("0x73", "GS Ball"),
    BLUE_CARD("0x74", "Blue Card*"),
    MIRACLE_SEED("0x75", "Miracle Seed"),
    THICK_CLUB("0x76", "Thick Club"),
    FOCUS_BAND("0x77", "Focus Band"),
    ENERGY_POWDER("0x79", "EnergyPowder"),
    ENERGY_ROOT("0x7A", "Energy Root"),
    HEAL_POWDER("0x7B", "Heal Powder"),
    REVIVAL_HERB("0x7C", "Revival Herb"),
    HARD_STONE("0x7D", "Hard Stone"),
    LUCKY_EGG("0x7E", "Lucky Egg"),
    CARD_KEY("0x7F", "Card Key"),
    MACHINE_PART("0x80", "Machine Part"),
    EGG_TICKET("0x81", "Egg Ticket*"),
    LOST_ITEM("0x82", "Lost Item"),
    STARDUST("0x83", "Stardust"),
    STAR_PIECE("0x84", "Star Piece"),
    BASEMENT_KEY("0x85", "Basement Key"),
    PASS("0x86", "Pass"),
    CHARCOAL("0x8A", "Charcoal"),
    BERRY_JUICE("0x8B", "Berry Juice"),
    SCOPE_LENS("0x8C", "Scope Lens"),
    METAL_COAT("0x8F", "Metal Coat"),
    DRAGON_FANG("0x90", "Dragon Fang"),
    LEFTOVERS("0x92", "Leftovers"),
    MYSTERY_BERRY("0x96", "Mystery Berry"),
    DRAGON_SCALE("0x97", "Dragon Scale"),
    BERSERK_GENE("0x98", "Berserk Gene"),
    SACRED_ASH("0x9C", "Sacred Ash"),
    HEAVY_BALL("0x9D", "Heavy Ball"),
    FLOWER_MAIL("0x9E", "Flower Mail"),
    LEVEL_BALL("0x9F", "Level Ball"),
    LURE_BALL("0xA0", "Lure Ball"),
    FAST_BALL("0xA1", "Fast Ball"),
    LIGHT_BALL("0xA3", "Light Ball"),
    FRIEND_BALL("0xA4", "Friend Ball"),
    MOON_BALL("0xA5", "Moon Ball"),
    LOVE_BALL("0xA6", "Love Ball"),
    NORMAL_BOX("0xA7", "Normal Box"),
    GORGEOUS_BOX("0xA8", "Gorgeous Box"),
    SUN_STONE("0xA9", "Sun Stone"),
    POLKADOT_BOW("0xAA", "Polkadot Bow"),
    UP_GRADE("0xAC", "Up-Grade"),
    BERRY("0xAD", "Berry"),
    GOLD_BERRY("0xAE", "Gold Berry"),
    SQUIRT_BOTTLE("0xAF", "SquirtBottle"),
    PARK_BALL("0xB1", "Park Ball"),
    RAINBOW_WING("0xB2", "Rainbow Wing"),
    BRICK_PIECE("0xB4", "Brick Piece"),
    SURF_MAIL("0xB5", "Surf Mail"),
    LITE_BLUE_MAIL("0xB6", "LiteBlue Mail"),
    PORTRAIT_MAIL("0xB7", "Portrait Mail"),
    LOVELY_MAIL("0xB8", "Lovely Mail"),
    EON_MAIL("0xB9", "Eon Mail"),
    MORPH_MAIL("0xBA", "Morph Mail"),
    BLUESKY_MAIL("0xBB", "Bluesky Mail"),
    MUSIC_MAIL("0xBC", "Music Mail"),
    MIRAGE_MAIL("0xBD", "Mirage Mail"),
    TM01("0xBF", "TM01"),
    TM02("0xC0", "TM02"),
    TM03("0xC1", "TM03"),
    TM04("0xC2", "TM04"),
    TM05("0xC4", "TM05"),
    TM06("0xC5", "TM06"),
    TM07("0xC6", "TM07"),
    TM08("0xC7", "TM08"),
    TM09("0xC8", "TM09"),
    TM10("0xC9", "TM10"),
    TM11("0xCA", "TM11"),
    TM12("0xCB", "TM12"),
    TM13("0xCC", "TM13"),
    TM14("0xCD", "TM14"),
    TM15("0xCE", "TM15"),
    TM16("0xCF", "TM16"),
    TM17("0xD0", "TM17"),
    TM18("0xD1", "TM18"),
    TM19("0xD2", "TM19"),
    TM20("0xD3", "TM20"),
    TM21("0xD4", "TM21"),
    TM22("0xD5", "TM22"),
    TM23("0xD6", "TM23"),
    TM24("0xD7", "TM24"),
    TM25("0xD8", "TM25"),
    TM26("0xD9", "TM26"),
    TM27("0xDA", "TM27"),
    TM28("0xDB", "TM28"),
    TM29("0xDD", "TM29"),
    TM30("0xDE", "TM30"),
    TM31("0xDF", "TM31"),
    TM32("0xE0", "TM32"),
    TM33("0xE1", "TM33"),
    TM34("0xE2", "TM34"),
    TM35("0xE3", "TM35"),
    TM36("0xE4", "TM36"),
    TM37("0xE5", "TM37"),
    TM38("0xE6", "TM38"),
    TM39("0xE7", "TM39"),
    TM40("0xE8", "TM40"),
    TM41("0xE9", "TM41"),
    TM42("0xEA", "TM42"),
    TM43("0xEB", "TM43"),
    TM44("0xEC", "TM44"),
    TM45("0xED", "TM45"),
    TM46("0xEE", "TM46"),
    TM47("0xEF", "TM47"),
    TM48("0xF0", "TM48"),
    TM49("0xF1", "TM49"),
    TM50("0xF2", "TM50"),
    HM01("0xF3", "HM01"),
    HM02("0xF4", "HM02"),
    HM03("0xF5", "HM03"),
    HM04("0xF6", "HM04"),
    HM05("0xF7", "HM05"),
    HM06("0xF8", "HM06"),
    HM07("0xF9", "HM07"),
    HM08("0xFA", "HM08"),
    HM09("0xFB", "HM09"),
    HM10("0xFC", "HM10"),
    HM11("0xFD", "HM11"),
    HM12("0xFE", "HM12");

    private final String hex;
    private final String name;

    Item(String hex, String name) {
        this.hex = hex;
        this.name = name;
    }

    public static Item valueOfHex(String hex) throws Exception {
        for (Item s : Item.values()) {
            if (s.hex.equals(hex)) {
                return s;
            }
        }
        throw new Exception("Cannot convert hex to type " + Item.class.getName());
    }

    @Override
    public String[] getHex() {
        return new String[] {hex};
    }

    @Override
    public String getName() {
        return name;
    }
}
