package com.russ4stall.pokemon;

/**
 * Created by russellf on 3/10/2016.
 */
public enum Species implements DataField {
    RHYDON("0x01", "Rhydon"),
    KANGASKHAN("0x02", "Kangaskhan"),
    NIDORAN_M("0x03", "Nidoran♂"),
    CLEFAIRY("0x04", "Clefairy"),
    SPEAROW("0x05", "Spearow"),
    VOLTORB("0x06", "Voltorb"),
    NIDOKING("0x07", "Nidoking"),
    SLOWBRO("0x08", "Slowbro"),
    IVYSAUR("0x09", "Ivysaur"),
    EXEGGUTOR("0x0A", "Exeggutor"),
    LICKITUNG("0x0B", "Lickitung"),
    EXEGGCUTE("0x0C", "Exeggcute"),
    GRIMER("0x0D", "Grimer"),
    GENGAR("0x0E", "Gengar"),
    NIDORAN_F("0x0F", "Nidoran♀"),
    NIDOQUEEN("0x10", "Nidoqueen"),
    CUBONE("0x11", "Cubone"),
    RHYHORN("0x12", "Rhyhorn"),
    LAPRAS("0x13", "Lapras"),
    ARCANINE("0x14", "Arcanine"),
    MEW("0x15", "Mew"),
    GYARADOS("0x16", "Gyarados"),
    SHELLDER("0x17", "Shellder"),
    TENTACOOL("0x18", "Tentacool"),
    GASTLY("0x19", "Gastly"),
    SCYTHER("0x1A", "Scyther"),
    STARYU("0x1B", "Staryu"),
    BLASTOISE("0x1C", "Blastoise"),
    PINSIR("0x1D", "Pinsir"),
    TANGELA("0x1E", "Tangela"),
    GROWLITHE("0x21", "Growlithe"),
    ONIX("0x22", "Onix"),
    FEAROW("0x23", "Fearow"),
    PIDGEY("0x24", "Pidgey"),
    SLOWPOKE("0x25", "Slowpoke"),
    KADABRA("0x26", "Kadabra"),
    GRAVELER("0x27", "Graveler"),
    CHANSEY("0x28", "Chansey"),
    MACHOKE("0x29", "Machoke"),
    MR_MIME("0x2A", "Mr. Mime"),
    HITMONLEE("0x2B", "Hitmonlee"),
    HITMONCHAN("0x2C", "Hitmonchan"),
    ARBOK("0x2D", "Arbok"),
    PARASECT("0x2E", "Parasect"),
    PSYDUCK("0x2F", "Psyduck"),
    DROWZEE("0x30", "Drowzee"),
    GOLEM("0x31", "Golem"),
    MAGMAR("0x33", "Magmar"),
    ELECTABUZZ("0x35", "Electabuzz"),
    MAGNETON("0x36", "Magneton"),
    KOFFING("0x37", "Koffing"),
    MANKEY("0x39", "Mankey"),
    SEEL("0x3A", "Seel"),
    DIGLETT("0x3B", "Diglett"),
    TAUROS("0x3C", "Tauros"),
    FARFETCHD("0x40", "Farfetch'd"),
    VENONAT("0x41", "Venonat"),
    DRAGONITE("0x42", "Dragonite"),
    DODUO("0x46", "Doduo"),
    POLIWAG("0x47", "Poliwag"),
    JYNX("0x48", "Jynx"),
    MOLTRES("0x49", "Moltres"),
    ARTICUNO("0x4A", "Articuno"),
    ZAPDOS("0x4B", "Zapdos"),
    DITTO("0x4C", "Ditto"),
    MEOWTH("0x4D", "Meowth"),
    KRABBY("0x4E", "Krabby"),
    VULPIX("0x52", "Vulpix"),
    NINETALES("0x53", "Ninetales"),
    PIKACHU("0x54", "Pikachu"),
    RAICHU("0x55", "Raichu"),
    DRATINI("0x58", "Dratini"),
    DRAGONAIR("0x59", "Dragonair"),
    KABUTO("0x5A", "Kabuto"),
    KABUTOPS("0x5B", "Kabutops"),
    HORSEA("0x5C", "Horsea"),
    SEADRA("0x5D", "Seadra"),
    SANDSHREW("0x60", "Sandshrew"),
    SANDSLASH("0x61", "Sandslash"),
    OMANYTE("0x62", "Omanyte"),
    OMASTAR("0x63", "Omastar"),
    JIGGLYPUFF("0x64", "Jigglypuff"),
    WIGGLYTUFF("0x65", "Wigglytuff"),
    EEVEE("0x66", "Eevee"),
    FLAREON("0x67", "Flareon"),
    JOLTEON("0x68", "Jolteon"),
    VAPOREON("0x69", "Vaporeon"),
    MACHOP("0x6A", "Machop"),
    ZUBAT("0x6B", "Zubat"),
    EKANS("0x6C", "Ekans"),
    PARAS("0x6D", "Paras"),
    POLIWHIRL("0x6E", "Poliwhirl"),
    POLIWRATH("0x6F", "Poliwrath"),
    WEEDLE("0x70", "Weedle"),
    KAKUNA("0x71", "Kakuna"),
    BEEDRILL("0x72", "Beedrill"),
    DODRIO("0x74", "Dodrio"),
    PRIMEAPE("0x75", "Primeape"),
    DUGTRIO("0x76", "Dugtrio"),
    VENOMOTH("0x77", "Venomoth"),
    DEWGONG("0x78", "Dewgong"),
    CATERPIE("0x7B", "Caterpie"),
    METAPOD("0x7C", "Metapod"),
    BUTTERFREE("0x7D", "Butterfree"),
    MACHAMP("0x7E", "Machamp"),
    GOLDUCK("0x80", "Golduck"),
    HYPNO("0x81", "Hypno"),
    GOLBAT("0x82", "Golbat"),
    MEWTWO("0x83", "Mewtwo"),
    SNORLAX("0x84", "Snorlax"),
    MAGIKARP("0x85", "Magikarp"),
    MUK("0x88", "Muk"),
    KINGLER("0x8A", "Kingler"),
    CLOYSTER("0x8B", "Cloyster"),
    ELECTRODE("0x8D", "Electrode"),
    CLEFABLE("0x8E", "Clefable"),
    WEEZING("0x8F", "Weezing"),
    PERSIAN("0x90", "Persian"),
    MAROWAK("0x91", "Marowak"),
    HAUNTER("0x93", "Haunter"),
    ABRA("0x94", "Abra"),
    ALAKAZAM("0x95", "Alakazam"),
    PIDGEOTTO("0x96", "Pidgeotto"),
    PIDGEOT("0x97", "Pidgeot"),
    STARMIE("0x98", "Starmie"),
    BULBASAUR("0x99", "Bulbasaur"),
    VENUSAUR("0x9A", "Venusaur"),
    TENTACRUEL("0x9B", "Tentacruel"),
    GOLDEEN("0x9D", "Goldeen"),
    SEAKING("0x9E", "Seaking"),
    PONYTA("0xA3", "Ponyta"),
    RAPIDASH("0xA4", "Rapidash"),
    RATTATA("0xA5", "Rattata"),
    RATICATE("0xA6", "Raticate"),
    NIDORINO("0xA7", "Nidorino"),
    NIDORINA("0xA8", "Nidorina"),
    GEODUDE("0xA9", "Geodude"),
    PORYGON("0xAA", "Porygon"),
    AERODACTYL("0xAB", "Aerodactyl"),
    MAGNEMITE("0xAD", "Magnemite"),
    CHARMANDER("0xB0", "Charmander"),
    SQUIRTLE("0xB1", "Squirtle"),
    CHARMELEON("0xB2", "Charmeleon"),
    WARTORTLE("0xB3", "Wartortle"),
    CHARIZARD("0xB4", "Charizard"),
    ODDISH("0xB9", "Oddish"),
    GLOOM("0xBA", "Gloom"),
    VILEPLUME("0xBB", "Vileplume"),
    BELLSPROUT("0xBC", "Bellsprout"),
    WEEPINBELL("0xBD", "Weepinbell"),
    VICTREEBEL("0xBE", "Victreebel");

    private final String hex;
    private final String name;

    Species(String hex, String name) {
        this.hex = hex;
        this.name = name;
    }

    public static Species valueOfHex(String hex) throws Exception {
        for (Species s : Species.values()) {
            if (s.hex.equals(hex)) {
                return s;
            }
        }
        throw new Exception("Cannot convert hex to type " + Species.class.getName());
    }

    @Override
    public String[] getHex() {
        return new String[] {hex};
    }

    @Override
    public String getName() {
        return name;
    }
}
